alter table "events" enable row level security;
create policy "public read access" on "events" for select to anon, authenticated using (true);
alter table "experts" enable row level security;
create policy "public read access" on "experts" for select to anon, authenticated using (true);
alter table "monthly_asset_class_outlook" enable row level security;
create policy "public read access" on "monthly_asset_class_outlook" for select to anon, authenticated using (true);
alter table "monthly_asset_performance" enable row level security;
create policy "public read access" on "monthly_asset_performance" for select to anon, authenticated using (true);
alter table "monthly_buy_list" enable row level security;
create policy "public read access" on "monthly_buy_list" for select to anon, authenticated using (true);
alter table "monthly_hot_issue" enable row level security;
create policy "public read access" on "monthly_hot_issue" for select to anon, authenticated using (true);
alter table "monthly_market_calendar" enable row level security;
create policy "public read access" on "monthly_market_calendar" for select to anon, authenticated using (true);
alter table "monthly_market_outlook" enable row level security;
create policy "public read access" on "monthly_market_outlook" for select to anon, authenticated using (true);
alter table "monthly_pdf" enable row level security;
create policy "public read access" on "monthly_pdf" for select to anon, authenticated using (true);
alter table "preview_asset_class_outlook" enable row level security;
create policy "public read access" on "preview_asset_class_outlook" for select to anon, authenticated using (true);
alter table "preview_hot_issue" enable row level security;
create policy "public read access" on "preview_hot_issue" for select to anon, authenticated using (true);
alter table "weekly_asset_performance" enable row level security;
create policy "public read access" on "weekly_asset_performance" for select to anon, authenticated using (true);
alter table "weekly_buy_list" enable row level security;
create policy "public read access" on "weekly_buy_list" for select to anon, authenticated using (true);
alter table "weekly_hot_issue" enable row level security;
create policy "public read access" on "weekly_hot_issue" for select to anon, authenticated using (true);
alter table "weekly_pdf" enable row level security;
create policy "public read access" on "weekly_pdf" for select to anon, authenticated using (true);